sources:
    - name: nouns
      handler:
          graphql:
              endpoint: https://api.thegraph.com/subgraphs/name/nounsdao/nouns-subgraph
              # endpoint: https://api.goldsky.com/api/public/project_cldf2o9pqagp43svvbk5u3kmo/subgraphs/nouns-v3-goerli/0.1.6/gn
      transforms:
          - autoPagination:
                validateSchema: true

documents:
    - ./src/queries/nouns-for-account.graphql
    - ./src/queries/noun-by-id.graphql
