sources:
    - name: nouns
      handler:
          graphql:
              endpoint: https://api.thegraph.com/subgraphs/name/nounsdao/nouns-subgraph
      transforms:
          - autoPagination:
                validateSchema: true

documents:
    - ./src/queries/nouns-for-account.graphql
    - ./src/queries/noun-by-id.graphql
